version: "3"
services:
  postgres:
    container_name: postgresFunds
    image: postgres:latest
    ports:
      - "6262:5432"
    volumes:
      - postgresData:/var/lib/postgresql/data
    env_file:
      - docker.env
    networks:
      - postgres

  pgadmin:
    links:
      - postgres:postgres
    container_name: pgadminFunds
    image: dpage/pgadmin4
    ports:
      - "6060:80"
    volumes:
      - /data/pgadmin:/root/.pgadmin
    env_file:
      - docker.env
    networks:
      - postgres

networks:
  postgres:
    driver: bridge

volumes:
  postgresData: {}
